CHROMEDRIVER_BUILDPACK_URL: https://github.com/heroku/heroku-buildpack-chromedriver
CHROMEDRIVER_PATH: /app/.chromedriver/bin/chromedriver
CURRENT_ENV: local
GOOGLE_CHROME_BUILDPACK_URL: https://github.com/heroku/heroku-buildpack-google-chrome
POSTGRES_PRODUCTION_PLAN: standard-0
PROCTYPE_PRODUCTION: standard-1x
REDIS_PRODUCTION_PLAN: premium-1
WEB_PRODUCTION_SCALE: '3'
WORKER: 'False'
WORKER_PRODUCTION_SCALE: '3'
